# contains all dependencies for running Cypress.io Test Runner
# https://on.cypress.io/docker and https://on.cypress.io/ci
#
FROM cmcg/bamboo-node:%VERSION%
LABEL org.opencontainers.image.authors="cmcgroarty@idesignconsulting.com"

USER root:root

# add ngsw-rehash
ADD https://github.com/dev-jan/ngsw-rehash/releases/download/v1.0/ngsw-rehash-linux-x86 $HOME/bin/ngsw-rehash
RUN chown -R $USERNAME:$USERNAME $HOME/bin
RUN chmod +x $HOME/bin/ngsw-rehash

USER $USERNAME:$USERNAME
